import type { FormField } from "@/components/common/DataForm";

export const communicationFields: FormField[] = [
  {
    name: "type",
    label: "Communication Type",
    type: "select",
    required: true,
    options: [
      { label: "Email", value: "EMAIL" },
      { label: "WhatsApp", value: "WHATSAPP" },
      { label: "SMS", value: "SMS" },
      { label: "Call", value: "CALL" },
      { label: "Meeting", value: "MEETING" },
      { label: "Note", value: "NOTE" },
    ],
  },
  {
    name: "recipient",
    label: "Recipient",
    type: "text",
    placeholder: "e.g., email@example.com or phone number",
    required: false,
  },
  {
    name: "subject",
    label: "Subject",
    type: "text",
    placeholder: "e.g., Proposal Follow-up",
    required: false,
  },
  {
    name: "message",
    label: "Message",
    type: "textarea",
    placeholder: "Enter communication details...",
    required: true,
    fullWidth: true,
  },
  {
    name: "customerId",
    label: "Customer",
    type: "select",
    options: [
      { label: "None", value: "" },
      { label: "Acme Corporation", value: "1" },
      { label: "Tech Solutions Inc", value: "2" },
      { label: "Global Enterprises", value: "3" },
      { label: "Future Tech Group", value: "4" },
      { label: "Innovation Labs", value: "5" },
      { label: "Digital Solutions", value: "6" },
      { label: "Enterprise Systems", value: "7" },
      { label: "Cloud Innovations", value: "8" },
    ],
  },
  {
    name: "leadId",
    label: "Lead",
    type: "select",
    options: [
      { label: "None", value: "" },
      { label: "Rahul Sharma - Sharma Enterprises", value: "lead-001" },
      { label: "Priya Verma - Verma Technologies", value: "lead-002" },
      { label: "Amit Gupta - Gupta Solutions", value: "lead-003" },
    ],
  },
  {
    name: "dealId",
    label: "Deal / Opportunity",
    type: "select",
    options: [
      { label: "None", value: "" },
      { label: "Enterprise Software License", value: "DL-001" },
      { label: "Cloud Migration Services", value: "DL-002" },
      { label: "Annual Support Contract", value: "DL-003" },
      { label: "Security Assessment", value: "DL-004" },
    ],
  },
  {
    name: "assignedTo",
    label: "Assigned To",
    type: "select",
    required: true,
    options: [
      { label: "Rahul Sharma", value: "emp-001" },
      { label: "Priya Verma", value: "emp-002" },
      { label: "Amit Kumar", value: "emp-003" },
      { label: "Neha Gupta", value: "emp-004" },
      { label: "Vikas Mehta", value: "emp-005" },
      { label: "Anjali Singh", value: "emp-006" },
      { label: "Rohit Yadav", value: "emp-007" },
      { label: "Simran Kaur", value: "emp-008" },
    ],
  },
  {
    name: "communicationDate",
    label: "Communication Date",
    type: "text",
    placeholder: "YYYY-MM-DD",
    required: true,
  },
  {
    name: "communicationTime",
    label: "Communication Time (Optional)",
    type: "text",
    placeholder: "e.g., 14:30",
  },
  {
    name: "status",
    label: "Status",
    type: "select",
    required: true,
    options: [
      { label: "Draft", value: "DRAFT" },
      { label: "Sent", value: "SENT" },
      { label: "Delivered", value: "DELIVERED" },
      { label: "Completed", value: "COMPLETED" },
      { label: "Failed", value: "FAILED" },
    ],
  },
];

