import type { FormField } from "@/components/common/DataForm";

export const campaignFields: FormField[] = [
  {
    name: "name",
    label: "Campaign Name",
    type: "text",
    placeholder: "e.g., Summer Sale 2026",
    required: true,
  },
  {
    name: "type",
    label: "Campaign Type",
    type: "select",
    required: true,
    options: [
      { label: "Email", value: "EMAIL" },
      { label: "WhatsApp", value: "WHATSAPP" },
      { label: "SMS", value: "SMS" },
    ],
  },
  {
    name: "status",
    label: "Campaign Status",
    type: "select",
    required: true,
    options: [
      { label: "Draft", value: "DRAFT" },
      { label: "Scheduled", value: "SCHEDULED" },
      { label: "Running", value: "RUNNING" },
      { label: "Completed", value: "COMPLETED" },
      { label: "Paused", value: "PAUSED" },
      { label: "Cancelled", value: "CANCELLED" },
    ],
  },
  {
    name: "audience",
    label: "Audience",
    type: "select",
    required: true,
    options: [
      { label: "All Customers", value: "ALL_CUSTOMERS" },
      { label: "All Leads", value: "ALL_LEADS" },
      { label: "Customers", value: "CUSTOMERS" },
      { label: "Leads", value: "LEADS" },
      { label: "Custom Audience", value: "CUSTOM" },
    ],
  },
  {
    name: "audienceCount",
    label: "Audience Count",
    type: "number",
    placeholder: "e.g., 100",
    required: false,
  },
  {
    name: "startDate",
    label: "Start Date",
    type: "text",
    placeholder: "YYYY-MM-DD",
    required: true,
  },
  {
    name: "endDate",
    label: "End Date",
    type: "text",
    placeholder: "YYYY-MM-DD",
    required: true,
  },
  {
    name: "assignedTo",
    label: "Assigned To",
    type: "select",
    required: true,
    options: [
      { label: "Rahul Sharma", value: "emp-001" },
      { label: "Priya Verma", value: "emp-002" },
      { label: "Amit Kumar", value: "emp-003" },
      { label: "Neha Gupta", value: "emp-004" },
      { label: "Vikas Mehta", value: "emp-005" },
      { label: "Anjali Singh", value: "emp-006" },
      { label: "Rohit Yadav", value: "emp-007" },
      { label: "Simran Kaur", value: "emp-008" },
    ],
  },
  {
    name: "budget",
    label: "Budget ($)",
    type: "number",
    placeholder: "e.g., 5000",
    required: false,
  },
  {
    name: "notes",
    label: "Notes",
    type: "textarea",
    placeholder: "Enter any additional notes...",
    fullWidth: true,
    required: false,
  },
  {
    name: "description",
    label: "Description",
    type: "textarea",
    placeholder: "Describe the campaign purpose and details...",
    fullWidth: true,
    required: false,
  },
];

