import type { FormField } from "@/components/common/DataForm";

export const payrollFields: FormField[] = [
  {
    name: "employeeId",
    label: "Employee ID",
    type: "text",
    placeholder: "Enter employee ID (e.g. emp-001)",
    required: true,
  },
  {
    name: "employeeName",
    label: "Employee Name",
    type: "text",
    placeholder: "Enter employee full name",
    required: true,
  },
  {
    name: "employeeCode",
    label: "Employee Code",
    type: "text",
    placeholder: "e.g. EMP-1001",
    required: true,
  },
  {
    name: "department",
    label: "Department",
    type: "select",
    placeholder: "Select department",
    required: true,
    options: [
      { label: "Sales", value: "Sales" },
      { label: "Human Resources", value: "Human Resources" },
      { label: "Engineering", value: "Engineering" },
      { label: "Marketing", value: "Marketing" },
      { label: "Finance", value: "Finance" },
      { label: "Support", value: "Support" },
      { label: "Design", value: "Design" },
      { label: "Administration", value: "Administration" },
      { label: "Operations", value: "Operations" },
    ],
  },
  {
    name: "designation",
    label: "Designation",
    type: "text",
    placeholder: "Enter job title",
    required: true,
  },
  {
    name: "basicSalary",
    label: "Basic Salary (₹)",
    type: "number",
    placeholder: "Enter basic salary amount",
    required: true,
  },
  {
    name: "payrollMonth",
    label: "Payroll Month",
    type: "select",
    placeholder: "Select month",
    required: true,
    options: [
      { label: "January", value: "1" },
      { label: "February", value: "2" },
      { label: "March", value: "3" },
      { label: "April", value: "4" },
      { label: "May", value: "5" },
      { label: "June", value: "6" },
      { label: "July", value: "7" },
      { label: "August", value: "8" },
      { label: "September", value: "9" },
      { label: "October", value: "10" },
      { label: "November", value: "11" },
      { label: "December", value: "12" },
    ],
  },
  {
    name: "payrollYear",
    label: "Payroll Year",
    type: "select",
    placeholder: "Select year",
    required: true,
    options: [
      { label: "2025", value: "2025" },
      { label: "2026", value: "2026" },
      { label: "2027", value: "2027" },
    ],
  },
  {
    name: "workingDays",
    label: "Working Days",
    type: "number",
    placeholder: "e.g. 22",
    required: true,
  },
  {
    name: "presentDays",
    label: "Present Days",
    type: "number",
    placeholder: "e.g. 20",
    required: true,
  },
  {
    name: "leaveDays",
    label: "Leave Days",
    type: "number",
    placeholder: "e.g. 2",
  },
  {
    name: "overtimeHours",
    label: "Overtime Hours",
    type: "number",
    placeholder: "e.g. 5",
  },
  {
    name: "overtimeAmount",
    label: "Overtime Amount (₹)",
    type: "number",
    placeholder: "e.g. 4000",
  },
  {
    name: "bonusAmount",
    label: "Bonus Amount (₹)",
    type: "number",
    placeholder: "Enter bonus amount",
  },
  {
    name: "deductions",
    label: "Deductions (₹)",
    type: "number",
    placeholder: "Enter total deductions",
    required: true,
  },
  {
    name: "status",
    label: "Status",
    type: "select",
    placeholder: "Select status",
    required: true,
    options: [
      { label: "Draft", value: "DRAFT" },
      { label: "Processing", value: "PROCESSING" },
      { label: "Processed", value: "PROCESSED" },
      { label: "Pending Approval", value: "PENDING_APPROVAL" },
      { label: "Approved", value: "APPROVED" },
      { label: "Paid", value: "PAID" },
    ],
  },
  {
    name: "notes",
    label: "Notes",
    type: "textarea",
    placeholder: "Enter any notes or remarks",
  },
];

